package com.youthloop.game.persistence.entity;

import lombok.Data;

/**
 * Game balance/scoring/ending config entity.
 */
@Data
public class GameBalanceRuleConfigEntity {
    private Integer configId;
    private String initialPhase;
    private Integer initialEventCooldown;
    private Integer boardSize;
    private Integer initialIndustry;
    private Integer initialTech;
    private Integer initialPopulation;
    private Integer initialGreen;
    private Integer initialCarbon;
    private Integer initialSatisfaction;
    private Integer initialLowCarbonScore;
    private Integer initialQuota;
    private Integer initialDrawEarly;
    private Integer drawCountEarly;
    private Integer drawCountMid;
    private Integer drawCountLate;
    private Integer eventCooldownResetTurns;
    private Integer settlementBaseIndustryGain;
    private Integer settlementBaseTechGain;
    private Integer settlementBasePopulationGain;
    private Integer satisfactionMax;
    private Integer carbonQuotaBaseLine;
    private Integer carbonQuotaPerNOver;
    private Integer carbonIndustryEmissionPerCard;
    private Integer carbonEcologyReductionPerCard;
    private Integer carbonScienceReductionPerCard;
    private Double tradeRandomBaseMin;
    private Double tradeRandomSpan;
    private Integer tradeHighCarbonThreshold;
    private Double tradeHighCarbonFactor;
    private Integer tradeLowCarbonThreshold;
    private Double tradeLowCarbonFactor;
    private Integer failureHighCarbonThreshold;
    private Integer failureHighCarbonStreakLimit;
    private Integer tradeFailureQuotaExhaustedLimit;
    private Double tradeFailureProfitThreshold;
    private Integer lowCarbonMinForPositiveEnding;
    private Integer lowCarbonDomainThreshold;
    private Integer lowCarbonDomainBonus;
    private Integer lowCarbonPolicyUnlockScore;
    private Integer lowCarbonPolicyUnlockAllCount;
    private Integer lowCarbonPolicyUnlockAllBonus;
    private Integer lowCarbonEventResolvedScore;
    private Integer lowCarbonEventTriggeredPenalty;
    private Integer lowCarbonOverLimitCarbonThreshold;
    private Integer lowCarbonOverLimitStreakThreshold;
    private Integer lowCarbonOverLimitStreakPenalty;
    private Double lowCarbonTradeProfitDivisor;
    private Integer lowCarbonTradeProfitBonus;
    private Integer lowCarbonQuotaExhaustedPenalty;
    private Integer lowCarbonInvalidOperationPenalty;
    private Integer carbonTier1Max;
    private Integer carbonTier1Score;
    private Integer carbonTier2Max;
    private Integer carbonTier2Score;
    private Integer carbonTier3Max;
    private Integer carbonTier3Score;
    private Integer carbonTier4Max;
    private Integer carbonTier4Score;
    private Integer carbonTier5Score;
    private Integer phaseEarlyMaxCards;
    private Integer phaseEarlyMaxScore;
    private Integer phaseMidMinCards;
    private Integer phaseMidMaxCards;
    private Integer phaseMidMinScore;
    private Integer phaseMidMaxScore;
    private Integer phaseLateMinCards;
    private Integer phaseLateMinScore;
    private Integer phaseLateRemainingCardsThreshold;
    private Double endingEventResolveRateRequired;
    private Integer endingInnovationMinScience;
    private Integer endingInnovationMinTech;
    private Integer endingInnovationMinLowCarbon;
    private Integer endingInnovationMaxCarbon;
    private Double endingInnovationMinProfit;
    private Integer endingEcologyMinEcology;
    private Integer endingEcologyMinGreen;
    private Integer endingEcologyMinLowCarbon;
    private Integer endingEcologyMaxCarbon;
    private Integer endingEcologyMinQuota;
    private Integer endingDoughnutMinSociety;
    private Integer endingDoughnutMinSatisfaction;
    private Integer endingDoughnutMinPopulation;
    private Integer endingDoughnutMinDomain;
    private Integer endingDoughnutMinLowCarbon;
    private Integer endingDoughnutMaxCarbon;
    private Integer endingDoughnutMinPolicyUsage6768;
    private Boolean isEnabled;
}
