-- ============================================================================
-- YouthLoop Game Schema Migration V003
-- Schema: game
-- Purpose: Initialize game card table and seed card catalog data
-- ============================================================================

CREATE TABLE IF NOT EXISTS game.game_card (
  card_id text PRIMARY KEY,
  card_no integer NOT NULL UNIQUE,
  name_zh text NOT NULL,
  name_en text NOT NULL,
  card_type text NOT NULL CHECK (card_type IN ('core', 'policy')),
  domain text NOT NULL CHECK (domain IN ('industry', 'ecology', 'science', 'society', 'policy')),
  star integer NOT NULL CHECK (star >= 1),
  phase_bucket text NOT NULL CHECK (phase_bucket IN ('early', 'mid', 'late', 'policy')),
  unlock_cost_industry integer NOT NULL DEFAULT 0 CHECK (unlock_cost_industry >= 0),
  unlock_cost_tech integer NOT NULL DEFAULT 0 CHECK (unlock_cost_tech >= 0),
  unlock_cost_population integer NOT NULL DEFAULT 0 CHECK (unlock_cost_population >= 0),
  unlock_cost_green integer NOT NULL DEFAULT 0 CHECK (unlock_cost_green >= 0),
  image_key text,
  advanced_image_key text,
  is_enabled boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_game_card_type_phase_enabled ON game.game_card(card_type, phase_bucket, is_enabled);
CREATE INDEX IF NOT EXISTS idx_game_card_domain_enabled ON game.game_card(domain, is_enabled);

INSERT INTO game.game_card (
  card_id,
  card_no,
  name_zh,
  name_en,
  card_type,
  domain,
  star,
  phase_bucket,
  unlock_cost_industry,
  unlock_cost_tech,
  unlock_cost_population,
  unlock_cost_green,
  image_key,
  advanced_image_key
)
VALUES
('card001', 1, '传统制造业', 'traditional_manufacturing', 'core', 'industry', 1, 'early', 0, 0, 0, 0, 'cards/basic/card001_traditional_manufacturing.webp', 'cards/advanced/card001_traditional_manufacturing.webp'),
('card002', 2, '服装加工产业', 'garment_processing_industry', 'core', 'industry', 1, 'early', 5, 0, 0, 0, 'cards/basic/card002_garment_processing_industry.webp', 'cards/advanced/card002_garment_processing_industry.webp'),
('card003', 3, '电子组装产业', 'electronic_assembly_industry', 'core', 'industry', 1, 'early', 8, 0, 0, 0, 'cards/basic/card003_electronic_assembly_industry.webp', 'cards/advanced/card003_electronic_assembly_industry.webp'),
('card004', 4, '食品加工产业', 'food_processing_industry', 'core', 'industry', 1, 'early', 6, 0, 0, 0, 'cards/basic/card004_food_processing_industry.webp', 'cards/advanced/card004_food_processing_industry.webp'),
('card005', 5, '高新产业', 'high_tech_industry', 'core', 'industry', 2, 'mid', 30, 0, 0, 0, 'cards/basic/card005_high_tech_industry.webp', 'cards/advanced/card005_high_tech_industry.webp'),
('card006', 6, '新能源汽车制造', 'new_energy_vehicle_manufacturing', 'core', 'industry', 2, 'mid', 35, 0, 0, 0, 'cards/basic/card006_new_energy_vehicle_manufacturing.webp', 'cards/advanced/card006_new_energy_vehicle_manufacturing.webp'),
('card007', 7, '半导体产业', 'semiconductor_industry', 'core', 'industry', 2, 'mid', 40, 0, 0, 0, 'cards/basic/card007_semiconductor_industry.webp', 'cards/advanced/card007_semiconductor_industry.webp'),
('card008', 8, '生物医药产业', 'biomedicine_industry', 'core', 'industry', 2, 'mid', 38, 0, 0, 0, 'cards/basic/card008_biomedicine_industry.webp', 'cards/advanced/card008_biomedicine_industry.webp'),
('card009', 9, '绿色产业园', 'green_industrial_park', 'core', 'industry', 3, 'late', 50, 10, 0, 0, 'cards/basic/card009_green_industrial_park.webp', 'cards/advanced/card009_green_industrial_park.webp'),
('card010', 10, '循环经济产业园', 'circular_economy_industrial_park', 'core', 'industry', 3, 'late', 55, 12, 0, 0, 'cards/basic/card010_circular_economy_industrial_park.webp', 'cards/advanced/card010_circular_economy_industrial_park.webp'),
('card011', 11, '跨境电商产业', 'cross_border_e_commerce_industry', 'core', 'industry', 2, 'early', 28, 0, 0, 0, 'cards/basic/card011_cross_border_e_commerce_industry.webp', 'cards/advanced/card011_cross_border_e_commerce_industry.webp'),
('card012', 12, '物流仓储产业', 'logistics_warehousing_industry', 'core', 'industry', 2, 'early', 25, 0, 0, 0, 'cards/basic/card012_logistics_warehousing_industry.webp', 'cards/advanced/card012_logistics_warehousing_industry.webp'),
('card013', 13, '智能家居制造', 'smart_home_manufacturing', 'core', 'industry', 2, 'mid', 32, 0, 0, 0, 'cards/basic/card013_smart_home_manufacturing.webp', 'cards/advanced/card013_smart_home_manufacturing.webp'),
('card014', 14, '新材料产业', 'new_materials_industry', 'core', 'industry', 2, 'mid', 36, 0, 0, 0, 'cards/basic/card014_new_materials_industry.webp', 'cards/advanced/card014_new_materials_industry.webp'),
('card015', 15, '人工智能产业', 'artificial_intelligence_industry', 'core', 'industry', 3, 'late', 60, 15, 0, 0, 'cards/basic/card015_artificial_intelligence_industry.webp', 'cards/advanced/card015_artificial_intelligence_industry.webp'),
('card016', 16, '无人机制造', 'drone_manufacturing', 'core', 'industry', 3, 'late', 58, 14, 0, 0, 'cards/basic/card016_drone_manufacturing.webp', 'cards/advanced/card016_drone_manufacturing.webp'),
('card017', 17, '机器人产业', 'robotics_industry', 'core', 'industry', 3, 'late', 62, 16, 0, 0, 'cards/basic/card017_robotics_industry.webp', 'cards/advanced/card017_robotics_industry.webp'),
('card018', 18, '光伏组件制造', 'photovoltaic_module_manufacturing', 'core', 'industry', 3, 'late', 55, 13, 0, 0, 'cards/basic/card018_photovoltaic_module_manufacturing.webp', 'cards/advanced/card018_photovoltaic_module_manufacturing.webp'),
('card019', 19, '产业升级基金', 'industrial_upgrade_fund', 'core', 'industry', 2, 'mid', 0, 0, 0, 0, 'cards/basic/card019_industrial_upgrade_fund.webp', 'cards/advanced/card019_industrial_upgrade_fund.webp'),
('card020', 20, '工业节能改造', 'industrial_energy_saving_retrofitting', 'core', 'industry', 2, 'mid', 20, 3, 0, 0, 'cards/basic/card020_industrial_energy_saving_retrofitting.webp', 'cards/advanced/card020_industrial_energy_saving_retrofitting.webp'),
('card021', 21, '天台绿化倡议', 'rooftop_greening_initiative', 'core', 'ecology', 1, 'early', 15, 0, 0, 0, 'cards/basic/card021_rooftop_greening_initiative.webp', 'cards/advanced/card021_rooftop_greening_initiative.webp'),
('card022', 22, '社区口袋公园', 'community_pocket_park', 'core', 'ecology', 1, 'early', 12, 0, 0, 0, 'cards/basic/card022_community_pocket_park.webp', 'cards/advanced/card022_community_pocket_park.webp'),
('card023', 23, '道路绿化升级', 'road_greening_upgrade', 'core', 'ecology', 1, 'early', 18, 0, 0, 0, 'cards/basic/card023_road_greening_upgrade.webp', 'cards/advanced/card023_road_greening_upgrade.webp'),
('card024', 24, '河道清淤工程', 'river_dredging_project', 'core', 'ecology', 1, 'early', 20, 0, 0, 0, 'cards/basic/card024_river_dredging_project.webp', 'cards/advanced/card024_river_dredging_project.webp'),
('card025', 25, '红树林修复', 'mangrove_restoration', 'core', 'ecology', 2, 'mid', 25, 0, 0, 0, 'cards/basic/card025_mangrove_restoration.webp', 'cards/advanced/card025_mangrove_restoration.webp'),
('card026', 26, '梧桐山森林抚育', 'wutong_mountain_forest_tending', 'core', 'ecology', 2, 'mid', 28, 0, 0, 0, 'cards/basic/card026_wutong_mountain_forest_tending.webp', 'cards/advanced/card026_wutong_mountain_forest_tending.webp'),
('card027', 27, '城中村绿墙改造', 'urban_village_green_wall_renovation', 'core', 'ecology', 2, 'early', 22, 0, 0, 0, 'cards/basic/card027_urban_village_green_wall_renovation.webp', 'cards/advanced/card027_urban_village_green_wall_renovation.webp'),
('card028', 28, '雨水花园建设', 'rain_garden_construction', 'core', 'ecology', 2, 'early', 24, 0, 0, 0, 'cards/basic/card028_rain_garden_construction.webp', 'cards/advanced/card028_rain_garden_construction.webp'),
('card029', 29, '海绵城市改造', 'sponge_city_renovation', 'core', 'ecology', 3, 'late', 20, 0, 0, 8, 'cards/basic/card029_sponge_city_renovation.webp', 'cards/advanced/card029_sponge_city_renovation.webp'),
('card030', 30, '海洋碳汇项目', 'marine_carbon_sink_project', 'core', 'ecology', 3, 'late', 30, 8, 0, 0, 'cards/basic/card030_marine_carbon_sink_project.webp', 'cards/advanced/card030_marine_carbon_sink_project.webp'),
('card031', 31, '全域绿建计划', 'global_green_building_plan', 'core', 'ecology', 2, 'late', 0, 0, 0, 0, 'cards/basic/card031_global_green_building_plan.webp', 'cards/advanced/card031_global_green_building_plan.webp'),
('card032', 32, '屋顶光伏覆盖', 'rooftop_photovoltaic_coverage', 'core', 'ecology', 2, 'mid', 26, 4, 0, 0, 'cards/basic/card032_rooftop_photovoltaic_coverage.webp', 'cards/advanced/card032_rooftop_photovoltaic_coverage.webp'),
('card033', 33, '湿地保护工程', 'wetland_protection_project', 'core', 'ecology', 2, 'mid', 29, 0, 0, 0, 'cards/basic/card033_wetland_protection_project.webp', 'cards/advanced/card033_wetland_protection_project.webp'),
('card034', 34, '碳汇林种植', 'carbon_sink_forest_planting', 'core', 'ecology', 2, 'mid', 23, 0, 0, 0, 'cards/basic/card034_carbon_sink_forest_planting.webp', 'cards/advanced/card034_carbon_sink_forest_planting.webp'),
('card035', 35, '生态修复专项基金', 'ecological_restoration_special_fund', 'core', 'ecology', 2, 'mid', 0, 0, 0, 0, 'cards/basic/card035_ecological_restoration_special_fund.webp', 'cards/advanced/card035_ecological_restoration_special_fund.webp'),
('card036', 36, '南科大实验室', 'sustech_laboratory', 'core', 'science', 1, 'early', 20, 0, 0, 0, 'cards/basic/card036_sustech_laboratory.webp', 'cards/advanced/card036_sustech_laboratory.webp'),
('card037', 37, '深大低碳研究院', 'szu_low_carbon_research_institute', 'core', 'science', 1, 'early', 18, 0, 0, 0, 'cards/basic/card037_szu_low_carbon_research_institute.webp', 'cards/advanced/card037_szu_low_carbon_research_institute.webp'),
('card038', 38, '碳捕捉技术', 'carbon_capture_technology', 'core', 'science', 2, 'mid', 30, 5, 0, 0, 'cards/basic/card038_carbon_capture_technology.webp', 'cards/advanced/card038_carbon_capture_technology.webp'),
('card039', 39, '智能电网技术', 'smart_grid_technology', 'core', 'science', 2, 'mid', 35, 6, 0, 0, 'cards/basic/card039_smart_grid_technology.webp', 'cards/advanced/card039_smart_grid_technology.webp'),
('card040', 40, '新能源电池研发', 'new_energy_battery_rd', 'core', 'science', 2, 'mid', 32, 5, 0, 0, 'cards/basic/card040_new_energy_battery_rd.webp', 'cards/advanced/card040_new_energy_battery_rd.webp'),
('card041', 41, '节能技术推广', 'energy_saving_technology_promotion', 'core', 'science', 2, 'mid', 28, 4, 0, 0, 'cards/basic/card041_energy_saving_technology_promotion.webp', 'cards/advanced/card041_energy_saving_technology_promotion.webp'),
('card042', 42, '零碳技术集群', 'zero_carbon_technology_cluster', 'core', 'science', 3, 'late', 40, 12, 0, 0, 'cards/basic/card042_zero_carbon_technology_cluster.webp', 'cards/advanced/card042_zero_carbon_technology_cluster.webp'),
('card043', 43, '碳足迹追踪系统', 'carbon_footprint_tracking_system', 'core', 'science', 3, 'late', 45, 15, 0, 0, 'cards/basic/card043_carbon_footprint_tracking_system.webp', 'cards/advanced/card043_carbon_footprint_tracking_system.webp'),
('card044', 44, '高校科研联动', 'university_research_collaboration', 'core', 'science', 2, 'early', 0, 5, 0, 0, 'cards/basic/card044_university_research_collaboration.webp', 'cards/advanced/card044_university_research_collaboration.webp'),
('card045', 45, '技术转化平台', 'technology_transfer_platform', 'core', 'science', 2, 'mid', 25, 6, 0, 0, 'cards/basic/card045_technology_transfer_platform.webp', 'cards/advanced/card045_technology_transfer_platform.webp'),
('card046', 46, '人才引进', 'talent_introduction', 'core', 'society', 1, 'early', 10, 0, 0, 0, 'cards/basic/card046_talent_introduction.webp', 'cards/advanced/card046_talent_introduction.webp'),
('card047', 47, '基础劳动力保障', 'basic_labor_force_guarantee', 'core', 'society', 1, 'early', 8, 0, 0, 0, 'cards/basic/card047_basic_labor_force_guarantee.webp', 'cards/advanced/card047_basic_labor_force_guarantee.webp'),
('card048', 48, '社区低碳公约', 'community_low_carbon_convention', 'core', 'society', 2, 'early', 5, 0, 2, 0, 'cards/basic/card048_community_low_carbon_convention.webp', 'cards/advanced/card048_community_low_carbon_convention.webp'),
('card049', 49, '共享出行网络', 'shared_mobility_network', 'core', 'society', 2, 'mid', 20, 0, 3, 0, 'cards/basic/card049_shared_mobility_network.webp', 'cards/advanced/card049_shared_mobility_network.webp'),
('card050', 50, '垃圾分类积分制', 'garbage_classification_points_system', 'core', 'society', 2, 'early', 15, 0, 2, 0, 'cards/basic/card050_garbage_classification_points_system.webp', 'cards/advanced/card050_garbage_classification_points_system.webp'),
('card051', 51, '老年友好社区', 'elderly_friendly_community', 'core', 'society', 2, 'mid', 18, 0, 2, 0, 'cards/basic/card051_elderly_friendly_community.webp', 'cards/advanced/card051_elderly_friendly_community.webp'),
('card052', 52, '青年创业扶持', 'youth_entrepreneurship_support', 'core', 'society', 3, 'late', 25, 0, 5, 0, 'cards/basic/card052_youth_entrepreneurship_support.webp', 'cards/advanced/card052_youth_entrepreneurship_support.webp'),
('card053', 53, '民生配套升级', 'livelihood_facilities_upgrade', 'core', 'society', 2, 'mid', 0, 0, 0, 0, 'cards/basic/card053_livelihood_facilities_upgrade.webp', 'cards/advanced/card053_livelihood_facilities_upgrade.webp'),
('card054', 54, '深圳碳市场试点', 'shenzhen_carbon_market_pilot', 'core', 'science', 2, 'late', 5, 3, 0, 0, 'cards/basic/card054_shenzhen_carbon_market_pilot.webp', 'cards/advanced/card054_shenzhen_carbon_market_pilot.webp'),
('card055', 55, '新能源汽车补贴', 'new_energy_vehicle_subsidy', 'core', 'industry', 2, 'early', 3, 2, 0, 0, 'cards/basic/card055_new_energy_vehicle_subsidy.webp', 'cards/advanced/card055_new_energy_vehicle_subsidy.webp'),
('card056', 56, '海绵城市专项补贴', 'sponge_city_special_subsidy', 'core', 'ecology', 2, 'mid', 2, 1, 0, 0, 'cards/basic/card056_sponge_city_special_subsidy.webp', 'cards/advanced/card056_sponge_city_special_subsidy.webp'),
('card057', 57, '产业升级补贴', 'industrial_upgrade_subsidy', 'core', 'industry', 2, 'mid', 4, 2, 0, 0, 'cards/basic/card057_industrial_upgrade_subsidy.webp', 'cards/advanced/card057_industrial_upgrade_subsidy.webp'),
('card058', 58, '全域协同计划', 'global_collaboration_plan', 'core', 'society', 3, 'late', 0, 0, 0, 0, 'cards/basic/card058_global_collaboration_plan.webp', 'cards/advanced/card058_global_collaboration_plan.webp'),
('card059', 59, '碳汇扶持政策', 'carbon_sink_support_policy', 'core', 'ecology', 2, 'mid', 4, 0, 0, 3, 'cards/basic/card059_carbon_sink_support_policy.webp', 'cards/advanced/card059_carbon_sink_support_policy.webp'),
('card060', 60, '零碳园区认定', 'zero_carbon_park_certification', 'core', 'industry', 3, 'late', 6, 4, 0, 0, 'cards/basic/card060_zero_carbon_park_certification.webp', 'cards/advanced/card060_zero_carbon_park_certification.webp'),
('card061', 61, '低碳产业补贴政策', 'low_carbon_industry_subsidy_policy', 'policy', 'policy', 2, 'policy', 0, 0, 0, 0, 'cards/policy/card061_low_carbon_industry_subsidy_policy.webp', NULL),
('card062', 62, '工业碳减排管控政策', 'industrial_carbon_reduction_control_policy', 'policy', 'policy', 2, 'policy', 0, 0, 0, 0, 'cards/policy/card062_industrial_carbon_reduction_control_policy.webp', NULL),
('card063', 63, '生态碳汇提升政策', 'ecological_carbon_sink_enhancement_policy', 'policy', 'policy', 2, 'policy', 0, 0, 0, 0, 'cards/policy/card063_ecological_carbon_sink_enhancement_policy.webp', NULL),
('card064', 64, '红树林保护专项政策', 'mangrove_protection_special_policy', 'policy', 'policy', 2, 'policy', 0, 0, 0, 0, 'cards/policy/card064_mangrove_protection_special_policy.webp', NULL),
('card065', 65, '科创低碳扶持政策', 'sci_tech_low_carbon_support_policy', 'policy', 'policy', 2, 'policy', 0, 0, 0, 0, 'cards/policy/card065_sci_tech_low_carbon_support_policy.webp', NULL),
('card066', 66, '碳捕捉技术推广政策', 'carbon_capture_technology_promotion_policy', 'policy', 'policy', 2, 'policy', 0, 0, 0, 0, 'cards/policy/card066_carbon_capture_technology_promotion_policy.webp', NULL),
('card067', 67, '甜甜圈社区建设政策', 'doughnut_community_construction_policy', 'policy', 'policy', 2, 'policy', 0, 0, 0, 0, 'cards/policy/card067_doughnut_community_construction_policy.webp', NULL),
('card068', 68, '市民低碳参与激励政策', 'citizen_low_carbon_participation_incentive_policy', 'policy', 'policy', 2, 'policy', 0, 0, 0, 0, 'cards/policy/card068_citizen_low_carbon_participation_incentive_policy.webp', NULL)
ON CONFLICT (card_id) DO UPDATE
SET
  card_no = EXCLUDED.card_no,
  name_zh = EXCLUDED.name_zh,
  name_en = EXCLUDED.name_en,
  card_type = EXCLUDED.card_type,
  domain = EXCLUDED.domain,
  star = EXCLUDED.star,
  phase_bucket = EXCLUDED.phase_bucket,
  unlock_cost_industry = EXCLUDED.unlock_cost_industry,
  unlock_cost_tech = EXCLUDED.unlock_cost_tech,
  unlock_cost_population = EXCLUDED.unlock_cost_population,
  unlock_cost_green = EXCLUDED.unlock_cost_green,
  image_key = EXCLUDED.image_key,
  advanced_image_key = EXCLUDED.advanced_image_key,
  updated_at = now();
