-- ============================================================================
-- YouthLoop Game Schema Migration V010
-- Schema: game
-- Purpose: Add balance/scoring/ending parameter config
-- ============================================================================

CREATE TABLE IF NOT EXISTS game.game_balance_rule_config (
  config_id smallint PRIMARY KEY CHECK (config_id = 1),
  initial_phase text NOT NULL DEFAULT 'early',
  initial_event_cooldown integer NOT NULL DEFAULT 0,
  board_size integer NOT NULL DEFAULT 6 CHECK (board_size >= 1),
  initial_industry integer NOT NULL DEFAULT 30,
  initial_tech integer NOT NULL DEFAULT 20,
  initial_population integer NOT NULL DEFAULT 25,
  initial_green integer NOT NULL DEFAULT 50,
  initial_carbon integer NOT NULL DEFAULT 80,
  initial_satisfaction integer NOT NULL DEFAULT 60,
  initial_low_carbon_score integer NOT NULL DEFAULT 0,
  initial_quota integer NOT NULL DEFAULT 50,
  initial_draw_early integer NOT NULL DEFAULT 4 CHECK (initial_draw_early >= 0),
  draw_count_early integer NOT NULL DEFAULT 4 CHECK (draw_count_early >= 0),
  draw_count_mid integer NOT NULL DEFAULT 3 CHECK (draw_count_mid >= 0),
  draw_count_late integer NOT NULL DEFAULT 2 CHECK (draw_count_late >= 0),
  event_cooldown_reset_turns integer NOT NULL DEFAULT 3 CHECK (event_cooldown_reset_turns >= 1),
  settlement_base_industry_gain integer NOT NULL DEFAULT 2,
  settlement_base_tech_gain integer NOT NULL DEFAULT 1,
  settlement_base_population_gain integer NOT NULL DEFAULT 1,
  satisfaction_max integer NOT NULL DEFAULT 200 CHECK (satisfaction_max >= 1),
  carbon_quota_base_line integer NOT NULL DEFAULT 80,
  carbon_quota_per_n_over integer NOT NULL DEFAULT 10 CHECK (carbon_quota_per_n_over >= 1),
  carbon_industry_emission_per_card integer NOT NULL DEFAULT 3,
  carbon_ecology_reduction_per_card integer NOT NULL DEFAULT 2,
  carbon_science_reduction_per_card integer NOT NULL DEFAULT 1,
  trade_random_base_min double precision NOT NULL DEFAULT 0.8,
  trade_random_span double precision NOT NULL DEFAULT 0.4,
  trade_high_carbon_threshold integer NOT NULL DEFAULT 100,
  trade_high_carbon_factor double precision NOT NULL DEFAULT 1.1,
  trade_low_carbon_threshold integer NOT NULL DEFAULT 60,
  trade_low_carbon_factor double precision NOT NULL DEFAULT 0.9,
  failure_high_carbon_threshold integer NOT NULL DEFAULT 130,
  failure_high_carbon_streak_limit integer NOT NULL DEFAULT 5 CHECK (failure_high_carbon_streak_limit >= 1),
  trade_failure_quota_exhausted_limit integer NOT NULL DEFAULT 4 CHECK (trade_failure_quota_exhausted_limit >= 1),
  trade_failure_profit_threshold double precision NOT NULL DEFAULT 0,
  low_carbon_min_for_positive_ending integer NOT NULL DEFAULT 120,
  low_carbon_domain_threshold integer NOT NULL DEFAULT 8,
  low_carbon_domain_bonus integer NOT NULL DEFAULT 5,
  low_carbon_policy_unlock_score integer NOT NULL DEFAULT 3,
  low_carbon_policy_unlock_all_count integer NOT NULL DEFAULT 8,
  low_carbon_policy_unlock_all_bonus integer NOT NULL DEFAULT 10,
  low_carbon_event_resolved_score integer NOT NULL DEFAULT 10,
  low_carbon_event_triggered_penalty integer NOT NULL DEFAULT 10,
  low_carbon_over_limit_carbon_threshold integer NOT NULL DEFAULT 80,
  low_carbon_over_limit_streak_threshold integer NOT NULL DEFAULT 3,
  low_carbon_over_limit_streak_penalty integer NOT NULL DEFAULT 15,
  low_carbon_trade_profit_divisor double precision NOT NULL DEFAULT 50,
  low_carbon_trade_profit_bonus integer NOT NULL DEFAULT 3,
  low_carbon_quota_exhausted_penalty integer NOT NULL DEFAULT 5,
  low_carbon_invalid_operation_penalty integer NOT NULL DEFAULT 8,
  carbon_tier_1_max integer NOT NULL DEFAULT 70,
  carbon_tier_1_score integer NOT NULL DEFAULT 3,
  carbon_tier_2_max integer NOT NULL DEFAULT 80,
  carbon_tier_2_score integer NOT NULL DEFAULT 0,
  carbon_tier_3_max integer NOT NULL DEFAULT 100,
  carbon_tier_3_score integer NOT NULL DEFAULT -2,
  carbon_tier_4_max integer NOT NULL DEFAULT 130,
  carbon_tier_4_score integer NOT NULL DEFAULT -5,
  carbon_tier_5_score integer NOT NULL DEFAULT -8,
  phase_early_max_cards integer NOT NULL DEFAULT 15,
  phase_early_max_score integer NOT NULL DEFAULT 59,
  phase_mid_min_cards integer NOT NULL DEFAULT 16,
  phase_mid_max_cards integer NOT NULL DEFAULT 30,
  phase_mid_min_score integer NOT NULL DEFAULT 60,
  phase_mid_max_score integer NOT NULL DEFAULT 100,
  phase_late_min_cards integer NOT NULL DEFAULT 31,
  phase_late_min_score integer NOT NULL DEFAULT 101,
  phase_late_remaining_cards_threshold integer NOT NULL DEFAULT 10,
  ending_event_resolve_rate_required double precision NOT NULL DEFAULT 70,
  ending_innovation_min_science integer NOT NULL DEFAULT 14,
  ending_innovation_min_tech integer NOT NULL DEFAULT 220,
  ending_innovation_min_low_carbon integer NOT NULL DEFAULT 170,
  ending_innovation_max_carbon integer NOT NULL DEFAULT 95,
  ending_innovation_min_profit double precision NOT NULL DEFAULT 120,
  ending_ecology_min_ecology integer NOT NULL DEFAULT 14,
  ending_ecology_min_green integer NOT NULL DEFAULT 140,
  ending_ecology_min_low_carbon integer NOT NULL DEFAULT 170,
  ending_ecology_max_carbon integer NOT NULL DEFAULT 70,
  ending_ecology_min_quota integer NOT NULL DEFAULT 30,
  ending_doughnut_min_society integer NOT NULL DEFAULT 12,
  ending_doughnut_min_satisfaction integer NOT NULL DEFAULT 92,
  ending_doughnut_min_population integer NOT NULL DEFAULT 110,
  ending_doughnut_min_domain integer NOT NULL DEFAULT 8,
  ending_doughnut_min_low_carbon integer NOT NULL DEFAULT 165,
  ending_doughnut_max_carbon integer NOT NULL DEFAULT 80,
  ending_doughnut_min_policy_usage_6768 integer NOT NULL DEFAULT 3,
  config_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_enabled boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_game_balance_rule_enabled
  ON game.game_balance_rule_config(is_enabled, config_id);

INSERT INTO game.game_balance_rule_config (
  config_id, config_snapshot
) VALUES (
  1,
  '{"initial":{"phase":"early","eventCooldown":0,"boardSize":6,"resources":{"industry":30,"tech":20,"population":25},"metrics":{"green":50,"carbon":80,"satisfaction":60,"lowCarbonScore":0},"quota":50},"draw":{"initialEarly":4,"early":4,"mid":3,"late":2},"phase":{"earlyMaxCards":15,"earlyMaxScore":59,"midMinCards":16,"midMaxCards":30,"midMinScore":60,"midMaxScore":100,"lateMinCards":31,"lateMinScore":101,"lateRemainingCardsThreshold":10},"trade":{"randomBaseMin":0.8,"randomSpan":0.4,"highCarbonThreshold":100,"highCarbonFactor":1.1,"lowCarbonThreshold":60,"lowCarbonFactor":0.9},"ending":{"lowCarbonMin":120}}'::jsonb
)
ON CONFLICT (config_id) DO UPDATE SET
  is_enabled = true,
  config_snapshot = EXCLUDED.config_snapshot,
  updated_at = now();
